### ISSUE TITLE
I am having problems with dotenv

### ISSUE THREAD

**Issue by AidanTheBandit** [rizkidn17/GenshinDiscordBot#1]
Hey so I am having this error with dotenv. Here is the error:
```
PS C:\Users\betha\Downloads\GenshinDiscordBot-master> & C:/Users/betha/AppData/Local/Microsoft/WindowsApps/python3.9.exe c:/Users/betha/Downloads/GenshinDiscordBot-master/GenshinDiscordBot-master/main.py
Traceback (most recent call last):
  File "c:\Users\betha\Downloads\GenshinDiscordBot-master\GenshinDiscordBot-master\main.py", line 7, in <module>
    from dotenv import DISCORD_TOKEN
ModuleNotFoundError: No module named 'dotenv'
PS C:\Users\betha\Downloads\GenshinDiscordBot-master> & C:/Users/betha/AppData/Local/Microsoft/WindowsApps/python3.9.exe c:/Users/betha/Downloads/GenshinDiscordBot-master/GenshinDiscordBot-master/main.py
Traceback (most recent call last):
  File "c:\Users\betha\Downloads\GenshinDiscordBot-master\GenshinDiscordBot-master\main.py", line 7, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
PS C:\Users\betha\Downloads\GenshinDiscordBot-master> 
```

**Comment by sqyo17** [comment]
Hello, probably you need to install "python-dotenv" package in repl.it project. 
Please let me know if it solve your problem or the problem still occur.

**Comment by AidanTheBandit** [comment]
I did install it

**Comment by sqyo17** [comment]
I just checked Rep.it, and it seems they change how the .env applied. 
In the side bar, i believe there is "Secret" menu. Fill it as:
key : DISCORD_TOKEN
value : yourdiscordtoken
Hope its help

**Comment by AidanTheBandit** [comment]
Oh. I’m supposed to use Rep.it. I was using it on my windows pc I then when I got it working was going to use ReviveNode

**Comment by sqyo17** [comment]
Oh hahaha. I use repl.it so i can host it free because its only for personal use(even tho seems the API owner rarely update, so i might looking for another API).
I think you can only take this repos as reference, because i really don't quite familiar with python environment in windows. 
Sorry i can not help you

**Comment by AidanTheBandit** [comment]
I’ll setup the bot on rep.it and tell you how it goes

**Comment by AidanTheBandit** [comment]
I added the secret thing but it is not showing up in the files list and when I run main.pay it says dotenv module doesn't exist

**Comment by AidanTheBandit** [comment]
Ok so I fixed it and modified the code so it works on Windows/Mac/Linux. Is there a way to add a Status to the bot? Like every 60 seconds it will be like "playing Boop, Watching Doot" something like that?
